### ISSUE TITLE
Restructure/simplify the install page

### ISSUE THREAD

**Issue by shwina** [rapidsai/rapids.ai#306]
The new install page (https://docs.rapids.ai/install) is nice because it has all the information someone would need to install RAPIDS. However, I think it could benefit from some restructuring:

1. Most users (especially return users) are going to just want a single install/setup command. I think it's important that the release selector be the very first thing people see when they navigate to this page. The details can come later.

2. The install steps for any particular type of installation are currently split between sections (2) and (3). Ideally, everything for Conda would be under a single section, everything for Docker would be under a single section, etc., so that I don't need to string together pieces from different sections for a particular installation method.

I'd propose the following page layout:

* Release Selector at the top
* System Requirements
* Installing with Conda
* Installing with Pip
* Installing with Docker
* Installing on Windows via WSL

In addition to outputting the "Command" for any particular install method, the release selector could also output a "Click here for details" link that would take the user to the particular section containing details for that method. For example, selecting `Docker` in the release selector would generate the docker commands, and for those who need more details, a link to the "Installing with Docker" section.

**Comment by bdice** [comment]
I love this idea. I had felt a similar tension with ease of use, and I think this is a great way to resolve it.

**Comment by vyasr** [comment]
I concur, this would be a big improvement. A couple of minor quibbles:
- The WSL2 should link to other sections as much as possible (already does for conda/pip/docker instructions IIRC)
- Not sure about the ordering between pip/docker and whether that's affected at all by pip only going GA in 23.04.

**Comment by exactlyallan** [comment]
@shwina Good suggestions - to consolidate and add on:
- Move the selector to the top ( with added title like "first time user? check requirements first" )
- In selector: Add note about min required driver version based on cuda version selection
- In selector: Add link to  install instructions based on install type
- In selector: Eventually Pip will be included once its no longer experimental
- Consolidate conda / docker / pip instructions together

**Comment by jarmak-nv** [comment]
Some notes from @bdice and me while we updated pip install anchors in https://github.com/rapidsai/docs/pull/372

I wondered if we should remove the "pip" part in 2A, but perhaps it's better served through the updates below.

----------
If pip is now part of the release selector, why do we need "3A Selector" and "3B pip"? Maybe the pip prerequisites should be in Section 2A "pip" instead of Section 3B?

----------
Can we use a nested structure for this "table of contents"? Something that looks more like:

![image](https://user-images.githubusercontent.com/3943761/233702969-dc05d4f8-d9a7-45b7-b660-b15fb3ef1422.png)


Then all the headings could have a proper home in the nested structure. See below. Note that I wouldn't use `i., ii., iii., iv.`. That's just how my comment is being formatted.

- Provision System
  1. Requirements
  2. System Recommendations
  3. Cloud Instance GPUs
- Set up Environment
  1. Conda
  2. Docker
  3. pip
  4. WSL 2
    a. Conda
    b. Docker
    c. pip
  5. Build from Source
- Install RAPIDS
  - Selector
  - Troubleshooting and Known Issues
- Getting Started _(I'd rename this to Next Steps)_

_Originally posted by @bdice in https://github.com/rapidsai/docs/pull/372#discussion_r1174033905_
